config/routes.rb
TaskBoard::Application.routes.draw do
  devise_for :users
  resources :boards
  resources :tasks
  resources :comments
  match 'assigned_to_me', :to => 'tasks#assigned_to_me', :as => 'assigned_to_me'

   root :to => 'welcome#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :description, :name, :user_id
  belongs_to :user
  has_many :tasks, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :task_id, :user_id
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :board_id, :description, :name, :status, :doc, :user_ids, :due_time, :task_time
  belongs_to :board
  belongs_to :user

  has_many :comments, :dependent => :destroy

  has_attached_file :doc
  do_not_validate_attachment_file_type :doc

  has_many :task_users
  has_many :users, :through => :task_users
  attr_reader :task_time

  after_update :send_task_status_mail

  def task_time=(time)
    if self.due_time.present? && time.present?
      self.due_time = "#{self.due_time.strftime("%Y-%m-%d")} #{time}"
    end
  end

  def task_time
    self.due_time.strftime("%I:%M %P") if self.due_time
  end

  private
  def send_task_status_mail
    if self.status_changed?
      AssignmentMailer.status_mail(self).deliver
    end
  end

end

app/models/task_user.rb
class TaskUser < ActiveRecord::Base
  set_table_name "tasks_users"
  attr_accessible :task_id, :user_id
  belongs_to :task
  belongs_to :user

  after_create :send_assignment_mail

  private
  def send_assignment_mail
    AssignmentMailer.assignment_mail(self).deliver
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :boards
  has_many :comments, :dependent => :destroy

  has_many :task_users
  has_many :tasks, :through => :task_users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    boards_url
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = current_user.boards
  end

  def show
    @board = Board.find(params[:id])
  end

  def edit
    @board = Board.find(params[:id])
  end
  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(params[:board])
      redirect_to boards_url, :notice => "Your Board has been updated successfully!"
    else
      render :edit
    end
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params[:board])
    @board.user = current_user

    if @board.save
      redirect_to boards_url, :notice => "Your Board has been created successfully!"
    else
      render :new
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_url, :notice => "Your Board has been deleted successfully!"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params[:comment])
    comment.save
    redirect_to :back, notice: "Your comment has been posted successfully!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.board_id = session[:board_id]
    @task.user = current_user
    if @task.save
      redirect_to tasks_url, :notice => "Your Task has been created successfully!"
    else
      render :new
    end
  end

  def index
    if params[:board_id].present?
      session[:board_id] = params[:board_id]
    end

    @board = Board.find(session[:board_id])
    @tasks = @board.tasks
    @tasks = @tasks.paginate(:page => params[:page], :per_page => 3)
    #@tasks = Task.where("board_id=?", params[:board_id])
  end

  def edit
    @task = Task.find(params[:id])
    session[:board_id] = @task.board_id
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      if @task.users.include?(current_user)
        redirect_to assigned_to_me_url ,:notice => "Your Task is Updated Successfully"
      else
        redirect_to tasks_url ,:notice => "Your Task is Updated Successfully"
      end
    else render :edit
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    TaskMailer.task_deleted_mail(@task).deliver
    @task.destroy
    redirect_to tasks_url, :notice => "Your Task is Deleted Successfully"
  end

  def assigned_to_me
    @tasks = current_user.tasks.paginate(:page => params[:page], :per_page => 3)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, '', class: "close glyphicon glyphicon-remove", title: 'Close', data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= form_for @board, {:url => board_url(@board), :html => {:method => :put}} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br /><br />
    <%= f.label :description  %>
    <%= f.text_area :description,:style => "width: 300px;height: 100px;" %> <br /><br />
    <%= f.submit  %>
<% end %>

app/views/boards/index.html.erb
<h1>My Board List</h1>

<table width="100%" class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
  <% @boards.each do |board| %>
     <tr>
       <td>
         <%= link_to board.name, tasks_url(:board_id => board.id), :class => 'board-title' %>
       </td>
       <td>
         <%= board.description[0..100] %> ...
       </td>
       <td style="width: 30%;">
         <%= link_to '<i class="glyphicon glyphicon-edit"></i> Edit'.html_safe, edit_board_url(board), {:class => 'btn btn-success action'} %>
         <%= link_to '<i class="glyphicon glyphicon-eye-open"></i> Show'.html_safe, board_url(board), :class => 'btn btn-info action' %>
         <%= link_to '<i class="glyphicon glyphicon-trash"></i> Delete'.html_safe, board_url(board), :method => :delete, :confirm => "Sure to delete?", :class => 'btn btn-danger action' %>
       </td>
     </tr>
  <% end %>
</table>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= form_for @board, {:url => boards_url, :html => {:method => :post}} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br /><br />
    <%= f.label :description %>
    <%= f.text_area :description, :style => "width: 300px;height: 100px;" %> <br /><br />
    <%= f.submit  %>
<% end %>

app/views/boards/show.html.erb
<p>
  <b>Name:</b> <%= @board.name %>
</p>

<p>
  <b>Description :</b> <%= @board.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskBoard</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">


  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "<b>Home</b>".html_safe, root_url, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %>
                  <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to '<i class="glyphicon glyphicon-off"></i> Sign Out'.html_safe, destroy_user_session_url, :method => :delete %></li>
                  <li><%= link_to "My Boards", boards_url %></li>
                  <li><%= link_to '<i class="glyphicon glyphicon-plus-sign"></i> Add Board'.html_safe, new_board_url %></li>
                  <li><%= link_to '<i class="glyphicon glyphicon-tags"></i> My Assigned Tasks'.html_safe, assigned_to_me_url %></li>
                  <li><%= link_to '<i class="glyphicon glyphicon-cog"></i> Settings'.html_safe, edit_user_registration_url %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign In", new_user_session_url %></li>
              <li><%= link_to "Sign Up", new_user_registration_url %></li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

  <%= flash_messages %>
  <%= yield %>

</div>
</body>
</html>

app/views/tasks/assigned_to_me.html.erb
<h1>My Assigned Tasks List</h1>

<table border="1" width="100%">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Board</th>
    <th>Status</th>
    <th>Attachment</th>
    <th>Expire Time</th>
    <th></th>

  </tr>
  <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= task.name %>
        </td>
        <td>
          <%= task.description[0..100] %>...

        </td>
        <td>
          <%= task.board.name %>

        </td>
        <td>
            <%=form_for task, :url => task_url(task), :html => {:method => :put} do |f| %>
                <%= f.collection_select :status, [['TODO','TODO'],['DOING','DOING'],['DONE','DONE']], :first, :last, {}, {:onchange => "this.form.submit()"} %>
            <% end %>
        </td>

        <td>
          <%= link_to task.doc.original_filename, task.doc.url if task.doc.present? %>
        </td>
        <td>
          <%= task.due_time.present? ? task.due_time.strftime("%d %B, %Y @ %I:%M %p") : 'Not Yet set' %>
        </td>
          <%= link_to "Show", task_url(task) %>
        </td>
      </tr>
  <% end %>
</table><br>
<%= will_paginate @tasks %><br>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1><br>
<%= form_for @task, {:url => task_url(@task), :html => {:method => :put}} do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br /><br />
    <%= f.label :description %>
    <%= f.text_area :description, :style => "width: 300px;height: 100px;" %> <br /><br />

    <%= f.label :due_time %>
    <%= f.text_field :due_time, :value => @task.due_time ? @task.due_time.strftime("%Y-%m-%d") : '' %>
    <%= f.text_field :task_time, :id=> 'task_time' %> <br /><br />

    <%= f.file_field :doc %> <br/><br/>

    <fieldset>
      <legend><strong>Assignment</strong></legend>
      <% User.all.each do |user| %>
       <input type="checkbox" value="<%= user.id%>" name="task[user_ids][]" <%= 'checked="checked"' if @task.users.include?(user) %> >  <%= user.email %> <br />
      <% end %>
    </fieldset>

    <%= f.submit  %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks List in <%= @board.name %></h1>

<table border="1" width="100%">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Attachment</th>
    <th>Created At</th>
    <th>Expire time At</th>
    <th></th>

  </tr>
  <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= task.name %>
        </td>
        <td>
          <%= task.description[0..100] %>...

        </td>
        <td>
          <%= task.status %>

         </td>

        <td>
          <%= link_to task.doc.original_filename, task.doc.url if task.doc.present? %>
        </td>
        <td>
          <%= task.created_at.strftime("%d %B, %Y @ %I:%M %p") %>
        </td>
        <td>
          <%= task.due_time.present? ? task.due_time.strftime("%d %B, %Y @ %I:%M %p") : 'Not Yet set' %>
        </td>
        <td>
          <%= link_to "Edit", edit_task_url(task) %>
          <%= link_to "Show", task_url(task) %>
          <%= link_to "Delete", task_url(task), :method => :delete, :confirm => "Sure to delete?" %>
        </td>
      </tr>
  <% end %>
</table><br>
<%= will_paginate @tasks %><br>
<%= link_to "New Task", new_task_url(:board_id => params[:board_id]) %>

app/views/tasks/new.html.erb
<h1>New Task</h1><br>
<%= form_for @task, {:url => tasks_url, :html => {:method => :post}} do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br /><br />
    <%= f.label :description %>
    <%= f.text_area :description, :style => "width: 300px; height: 100px;" %> <br /><br />
    <%= f.label :due_time %>
    <%= f.text_field :due_time, :value => @task.due_time ? @task.due_time.strftime("%Y-%m-%d") : '' %>
    <%= f.text_field :task_time, :id=> 'task_time' %> <br /><br />

    <%= f.hidden_field :board_id %>
    <%= f.file_field :doc %>
    <br /><br />
    <fieldset>
      <legend><strong>Assignment</strong></legend>
      <% User.all.each do |user| %>
          <input type="checkbox" value="<%= user.id%>" name="task[user_ids][]" <%= 'checked="checked"' if @task.users.include?(user) %> >  <%= user.email %> <br />
      <% end %>
    </fieldset>

    <%= f.submit  %>
<% end %>


app/views/tasks/show.html.erb
<p>
  <b>Name:</b> <%= @task.name %>
</p>

<p>
  <b>Description :</b> <%= @task.description %>
</p>

<p>
  <strong>Assigned On:</strong>
  <% @task.users.each do |user| %>
    <div><%= user.email %></div>
  <% end %>
</p>

<p>
  <strong>Comments:</strong>
  <% @task.comments.each do |comment| %>
   <div style="border: 1px solid #CCCCCC;padding: 7px;">
     <%= comment.description %>
   </div>
  <% end %>
</p>

<% if user_signed_in? %>
<%= form_for Comment.new, :url => comments_url, :html => {:method => :post} do |f| %>
  <%= f.label :description, 'Comment' %>
  <%= f.text_area :description, :style => "width: 380px;height: 80px" %> <br /><br />
  <%= f.hidden_field :task_id, :value => @task.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit %>
<% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>
  Wellcome To Task Board
</h1>